spring:
  main.allow-bean-definition-overriding: true
  sql:
    init:
      schema-locations: sql/schema.sql
      data-locations: sql/data.sql
  datasource:
    driverClassName: org.h2.Driver
    jdbc-url: jdbc:h2:mem:mydb;
    username: root
    password: root
  h2:
    console:
      enabled: true
